In [1]:
import numpy as np
import pandas as pd
import tushare as ts

## 获得300个成分股近3年的日行情数据

In [2]:
ts.set_token('35f337e592e9520154d2a0827c491f75ccc87b723d2bec02cea6b78b')
pro = ts.pro_api()

In [10]:
df_300_w=pd.read_excel("000300closeweight.xlsx")
df_300_w=df_300_w[['成份券代码Constituent Code','成份券名称Constituent Name','交易所Exchange','权重(%)weight']]
df_300_w.head()

   成份券代码Constituent Code 成份券名称Constituent Name 交易所Exchange  权重(%)weight
0                 600519                  贵州茅台     上海证券交易所        4.767
1                 300750                  宁德时代     深圳证券交易所        3.430
2                 601318                  中国平安     上海证券交易所        2.851
3                 600036                  招商银行     上海证券交易所        2.238
4                 300059                  东方财富     深圳证券交易所        1.713

In [12]:
df_300_w["地区"]=df_300_w["交易所Exchange"].map({
    "上海证券交易所":'SH',
    "深圳证券交易所":'SZ'
})
df_300_w["ts_code"]=df_300_w.apply(lambda x:str(x["成份券代码Constituent Code"])+"."+x["地区"],axis=1)
df_300_w.head()

,成份券代码Constituent Code,成份券名称Constituent Name,交易所Exchange,权重(%)weight,地区,ts_code
0,600519,贵州茅台,上海证券交易所,4.767,SH,600519.SH
1,300750,宁德时代,深圳证券交易所,3.430,SZ,300750.SZ
2,601318,中国平安,上海证券交易所,2.851,SH,601318.SH
3,600036,招商银行,上海证券交易所,2.238,SH,600036.SH
4,300059,东方财富,深圳证券交易所,1.713,SZ,300059.SZ

In [14]:
ts_cod=df_300_w["ts_code"].tolist()
cols=['ts_code','trade_date','open','high','low','close','pre_close','change','pct_chg','vol','amount']
df_all=pd.DataFrame(columns=cols)
for cd in ts_cod:
    df_i = pro.daily(ts_code=cd, start_date='20211210', end_date='20241211')
    df_all=pd.concat([df_all, df_i]).reset_index(drop=True)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_45900\3734932550.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all=pd.concat([df_all, df_i]).reset_index(drop=True)

In [15]:
df_all.to_excel("df_all.xlsx")

In [9]:
# df_300=pd.read_excel("沪深300指数近3年.xlsx")
# df_300.head()

H:\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,日期Date,指数代码Index Code,指数中文全称Index Chinese Name(Full),指数中文简称Index Chinese Name,指数英文全称Index English Name(Full),指数英文简称Index Chinese Name,开盘Open,最高High,最低Low,收盘Close,涨跌Change,涨跌幅(%)Change(%),成交量（万手）Volume(M Shares),成交金额（亿元）Turnover,样本数量ConsNumber
0,20211210,300,沪深300指数,沪深300,CSI 300 Index,CSI 300,5046.27,5060.06,5035.81,5055.12,-23.57,-0.46,19369.52,3569.18,300
1,20211213,300,沪深300指数,沪深300,CSI 300 Index,CSI 300,5090.02,5143.84,5079.73,5083.80,28.68,0.57,21180.16,4263.77,300
2,20211214,300,沪深300指数,沪深300,CSI 300 Index,CSI 300,5066.35,5075.21,5038.86,5049.70,-34.11,-0.67,15910.78,3186.86,300
3,20211215,300,沪深300指数,沪深300,CSI 300 Index,CSI 300,5036.28,5060.37,5003.78,5005.90,-43.80,-0.87,15052.98,2910.73,300
4,20211216,300,沪深300指数,沪深300,CSI 300 Index,CSI 300,5006.61,5034.73,4987.22,5034.73,28.83,0.58,14405.39,2914.75,300